spring:
  thymeleaf:
    cache: false

logging:
  path: ${LOG_PATH:logs}
  pattern:
    console: '%date{HH:mm:ss.SSS} %highlight(%-5p) [%t] %C{0}.%M:%L %msg%xEx%n'
    file: '%date{HH:mm:ss.SSS} %-5p [%t] %C{0}.%M:%L %msg%xEx%n'
  level:
    org.hibernate.SQL: DEBUG
    com.dashuf.dsres: DEBUG
