server.port: 8080

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://d0cbli.mysql.dbdev.dsfdc.com:5011/chu?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: deployop
    password: DDeployop88#
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: E:/IdeaProjects/logs/springboot
  pattern:
    console: '%date{HH:mm:ss.SSS} %highlight(%-5p) [%t] %C{0}.%M:%L %msg%xEx%n'
    file: '%date{HH:mm:ss.SSS} %-5p [%t] %C{0}.%M:%L %msg%xEx%n'
  level:
    org.hibernate.SQL: DEBUG
    com.chu: DEBUG

---

spring:
  profiles: dev

amazon.associateId: dev

---

spring:
  profiles: prd

amazon.associateId: prd